language: php
php:
- 7.0
before_script:
- composer install --no-interaction
script:
- composer covd
deploy:
  api_key:
    secure: dusYY6Yg/dJMV8mXJbqhShQ507h+K5vyUsInRXuYlNiG8DgnZZh1IazZ2nAbTW+FTYadpziE0NXhoFr5J3/w5zR6jFTRA0eRi6KxdiUQ5xFnE9e0OspgUBFM+eav/Pxakxfd/5nBVqy/viUnkXhrVtEfSiipGYoalW3BGcyJd/jl4d74krxZ13/8zolY42WsXqPqBy75eTv5dczmgbUgGy4GWfV8Dj3e6YRJHy+eAfb92oeYH4vyDhJXu3vwdbbIOx0nIXyIikYY6OLQO+8eYKzfzTNsOf7rt7DV/n79yL3Nf8hzBgxkQ5zj1s5/uylEpljBkNdgxxq6AgtVLogarUqkkDpSRstDkhqPXQBn8ppV56TOP51i1uogUApk0wW3fsnHPFb2gGSfx5Bia5GOtvPg8a8vbrhPlzxIOY23v0D2oLlpB6K69XzeKY30LKPS0UMs7JKvABNuXExRI2UQUvBAyQUuu2X0wK1Lz/RfH+qIfJYk0zlCnk2c9vyzs28p5ps7w3aMxd1OFaN/WlNNTxPvCYmZH5iCD8B7iN+kY+GSyUf7AIV+8bvTPfaxu+E7tNXiKbKsMJEZ2NCLIFNM2U9zkVVSHVUAJGqVuy48OvT74XFM3G4zMIDkn5TpWqfBYz/eaBhnqgfsHBMxt/69YnjjH91nxLVRLNQ2JxNi6PU=
